product:
  name: Product Service Dev Update
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
app:
  testProp: TestProp Prueba